- id: branching-check
  name: Check branching strategies
  description: Check branch matching your requirement
  entry: pre_commit_hooks/branching.sh
  pass_filenames: false
  language: script
  types: [shell]

- id: msg-check
  name: Check msg strategies
  description: Check msg matching your requirement
  entry: pre_commit_hooks/msg.sh
  pass_filenames: false
  language: script
  types: [shell]