---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: branching-check
  name: Check branching strategies
  description: Check branch matching your requirement
  entry: pre_commit_hooks/branching.sh 
  language: script
  # files: [files]
  verbose: true
  always_run: true
  pass_filenames: false

- id: msg-check
  name: Check msg strategies
  description: Check msg matching your requirement
  entry: pre_commit_hooks/msg.sh
  language: script
  always_run: true
  pass_filenames: false
  verbose: true
