- id: branching-check
  name: Check branching strategies
  verbose: true
  args:
    - -p=^(dev|release|staging).*$
  description: Check branch matching your requirement
  entry: pre_commit_hooks/branching.sh 
  language: script
  always_run: true
  pass_filenames: false

- id: msg-check
  verbose: true
  name: Check msg strategies
  args:
  - -p=^(dev|release|staging).*$
  description: Check msg matching your requirement
  entry: pre_commit_hooks/msg.sh
  language: script
  always_run: true
  pass_filenames: false
